{
 "title": "アクセスログ",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "500レスポンス",
   "type": "logs",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"access_logs\"} |~ `/api/[^/]+` != `/manage/api/health` | pattern `/var/log/server/<rack>/<host>/LOG/<log_month>/access_log.gz_<log_date>:<ip> - - [<date>:<timestamp> <offset>] <responsetime> \"<method> <path> HTTP/1.1\" <status> <size> \"<referrer>\" \"<agent>\"` | status = `500`"
    }
   ]
  },
  {
   "title": "APIのみ_charge/summary除く フォーマット",
   "type": "logs",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"access_logs\"} |~ `/api/[^/]+` != `/manage/api/health` != `/api/charge/summary` | pattern `/var/log/server/<rack>/<host>/LOG/<log_month>/access_log.gz_<log_date>:<ip> - - [<date>:<timestamp> <offset>] <responsetime> \"<method> <path> HTTP/1.1\" <status> <size> \"<referrer>\" \"<agent>\"` | line_format `{{.host}} {{.date}} {{.timestamp}} {{.status}} {{.size}} {{.method}} {{.path}} {{.referrer}} {{.agent}}`"
    }
   ]
  },
  {
   "title": "レスポンス時間 > 5秒",
   "type": "logs",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"access_logs\"} |~ `/api/[^/]+` != `/manage/api/health` | pattern `/var/log/server/<rack>/<host>/LOG/<log_month>/access_log.gz_<log_date>:<ip> - - [<date>:<timestamp> <offset>] <responsetime> \"<method> <path> HTTP/1.1\" <status> <size> \"<referrer>\" \"<agent>\"` | responsetime > 5000000"
    }
   ]
  },
  {
   "title": "アクセスログ",
   "type": "logs",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"access_logs\"} != `/manage/api/health` != `/server-status` | pattern `<logfile>:<ip> - - [<date>:<timestamp> <offset>] <responsetime> \"<method> <path> HTTP/1.1\" <status> <size> \"<referrer> \"<agent>\"`"
    }
   ]
  }
 ]
}