{
 "title": "APIリクエスト数",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "分間APIリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"access_logs\"} != `/manage/api/health` |~ `\"[^ ]+ /[^/]+/api/` != `/api/charge/summary` [1m]))",
     "legendFormat": "api requests"
    }
   ]
  },
  {
   "title": "テナントのAPIリクエスト数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "count by(prefix) (rate({job=\"access_logs\"} != `/manage/api/health` |~ `\"[^ ]+ /[^/]+/api/` != `/api/charge/summary` [1h]))"
    }
   ]
  },
  {
   "title": "APIアクセス数",
   "type": "barchart",
   "gridPos": { "h": 23, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "topk(40, sum by(path) (count_over_time({job=\"access_logs\"} | path != `` | path != `/health` [${__range}])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "エンドポイントごとの1hアクセス数",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(method, path) (count_over_time({job=\"access_logs\"} != `/manage/api/health` |= `/api/` | path != `/charge/summary` [1h]))"
    }
   ]
  },
  {
   "title": "10分間_高負荷API頻度(入金/請求/顧客/MT取込,照合.一括消込)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({job=\"access_logs\"} | path =~ `(/receipt/imports|/receipt/mt-imports|/billing/imports|/customer/imports|/receipt/mt-imports|/reconciliation/reconciliate|/clearing/bulkClearing)` [10m]))"
    }
   ]
  }
 ]
}