server:
  log_level: info
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml
  
clients:
  - url: http://loki:3100/loki/api/v1/push

components:
  # 1. File discovery component to find log files
  - name: file_watcher
    kind: file
    paths:
      - /logs/*.log
    labels:
      job: access_logs
      source: access_logs

flow:
  # File watcher output
  - from: file_watcher
    
    # Processing pipeline (equivalent to promtail pipeline stages)
    process:
      # 1) Extract timestamp
      - regex:
          expression: '\[(?P<timestamp>\d{2}/\w+/\d{4}:\d{2}:\d{2}:\d{2} [+-]\d{4})\]'
      - timestamp:
          source: timestamp
          format: "02/Jan/2006:15:04:05 -0700"
      
      # 2) Extract method, prefix, path from HTTP request
      - regex:
          expression: '"(?P<method>GET|PUT|POST|HEAD|DELETE|PATCH|OPTIONS|CONNECT|TRACE|QUERY) /(?P<prefix>[^/]+)/api(?P<path>/[^ ?"]+)'
      
      # 3) Replace numeric IDs in path
      - replace:
          expression: "(/[0-9]+)"
          source: path
          replace: "/:id"
      
      # 4) Add extracted fields as labels
      - labels:
          method:
          prefix:
          path:
    
    # Send to Loki
    to: loki