version: '3.7'

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config:/etc/loki
      - loki-data:/tmp/loki
      - loki-wal:/tmp/wal
    user: "0:0"  # Run as root to avoid permission issues

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./logs:/logs
      - ./request_logs:/request_logs  # Mount request_logs directory
      - ./alloy/conf:/etc/alloy/conf  # Updated path to config.alloy
      - ./alloy/cert:/etc/alloy/cert  # Mount certificate directory
      - ./alloy/scripts:/etc/alloy/scripts  # Mount scripts directory
      - alloy-positions:/tmp/positions
    command: >
      run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/tmp/data
      /etc/alloy/conf/config.alloy
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

volumes:
  grafana-storage:
  loki-data:
  loki-wal:
  alloy-positions:  # Volume for alloy positions